name: Code linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest
    concurrency: ci-test-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lib:lint
